---
# tasks file for http_setup
- name: httpd
  apt:
    name: "{{ http_package_name }}"
    state: present
  become: true

- name: copy file
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: start service
  service:
    name: "{{ http_package_name }}"
    state: present
    enable: true
  become: true
