---
- name: Install apache
  hosts: webhooks
  become: true
  vars:
    app: httpd

  tasks:
    - name: "{{ app }}"
      apt:
        state: present
    - name: "{{ app }}"
      service:
        state: started
        enabled: true
