---
- name: cronjob
  hosts: webhooks

  tasks:
    - name: Add cron job
      cron:
        name: Run test script
        minute: 05
        hour: 22
        day: 13
        month: "*"
        weekday: "*"
        user: ubuntu
        job: "/home/ubuntu/test.sh"
        #disabled: true # for disable cronjob
